### ISSUE TITLE
Outcome 3D variables in RealTime Run

### ISSUE THREAD

**Issue by c-hydro** [c-hydro/hmc-dev#7]
Problems with real-time simulations:
3d variable are not fine for real-time mode because each time step is saved with 3D variables; a flag to select variables in basic/extended in order to save 
1) for climatic run --> basic variables dataset [Q, ET, VTot, Flooding]
2) for real-time run --> extended variables dataset  [ALL]

A computation of daily max have to be removed in outcome gridded subroutine.

The computation of 3D variables is done in:
1) ET subroutine (ET)
2) Convolution subroutines (Q and Flooding)

In outcome subroutine the 3D variables have to be replace by 2D variables with the
same meaning.

**Comment by fabiodelogu** [comment]
fix
